-- MySQL Script generated by MySQL Workbench
-- Sun Sep 13 11:04:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema djary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema djary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `djary` DEFAULT CHARACTER SET utf8 ;
USE `djary` ;

-- -----------------------------------------------------
-- Table `djary`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFinal` DATE NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `ubicacion` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`subevento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`subevento` (
  `id_subevento` INT NOT NULL AUTO_INCREMENT,
  `id_evento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NOT NULL,
  `ubicacion` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_subevento`),
  CONSTRAINT `fk_subevento_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `djary`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`actividad` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `id_subevento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NOT NULL,
  PRIMARY KEY (`id_actividad`),
  CONSTRAINT `fk_actividad_subevento1`
    FOREIGN KEY (`id_subevento`)
    REFERENCES `djary`.`subevento` (`id_subevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`ponente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`ponente` (
  `id_ponente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `informacionAcademica` MEDIUMTEXT NOT NULL,
  `correoElectronico` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_ponente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`material` (
  `id_material` INT NOT NULL,
  `id_actividad` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `stock` INT NOT NULL,
  `costo` INT NOT NULL,
  PRIMARY KEY (`id_material`),
  CONSTRAINT `fk_material_actividad1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `djary`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`registroMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`registroMaterial` (
  `id_material` INT NOT NULL,
  `fecha` DATE NOT NULL,
  CONSTRAINT `fk_registroMaterial_material`
    FOREIGN KEY (`id_material`)
    REFERENCES `djary`.`material` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`comite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`comite` (
  `id_comite` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcionFuncion` TINYTEXT NOT NULL,
  PRIMARY KEY (`id_comite`),
  CONSTRAINT `fk_comite_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `djary`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`personal` (
  `id_personal` INT NOT NULL,
  `id_comite` INT NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_personal`),
  CONSTRAINT `fk_mienbros_comite1`
    FOREIGN KEY (`id_comite`)
    REFERENCES `djary`.`comite` (`id_comite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`caja` (
  `id_caja` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `dinero` DOUBLE NOT NULL,
  PRIMARY KEY (`id_caja`, `id_evento`),
  CONSTRAINT `fk_caja_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `djary`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`registroCaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`registroCaja` (
  `id_registroCaja` INT NOT NULL,
  `id_caja` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `monto` DOUBLE NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `descripcion` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_registroCaja`),
  CONSTRAINT `fk_registroCaja_caja1`
    FOREIGN KEY (`id_caja`)
    REFERENCES `djary`.`caja` (`id_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`ambiente` (
  `id_ambiente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `puertasEmergencias` INT NOT NULL,
  `aforo` INT NOT NULL,
  `pais` VARCHAR(15) NOT NULL,
  `distrito` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_ambiente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`asiganrAmbiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`asiganrAmbiente` (
  `id_actividad` INT NOT NULL,
  `id_ambiente` INT NOT NULL,
  CONSTRAINT `fk_asiganrAmbiente_ambiente1`
    FOREIGN KEY (`id_ambiente`)
    REFERENCES `djary`.`ambiente` (`id_ambiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asiganrAmbiente_actividad1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `djary`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `credencial` VARCHAR(21) NOT NULL,
  `numeroCredencial` VARCHAR(15) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `categoria` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`admin` (
  `id_admin` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `credencial` VARCHAR(21) NOT NULL,
  `numeroCredencial` VARCHAR(15) NOT NULL,
  `admincol` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`asignarPonente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`asignarPonente` (
  `id_actividad` INT NOT NULL,
  `id_ponente` INT NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  CONSTRAINT `fk_asignarPonente_actividad1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `djary`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignarPonente_ponente1`
    FOREIGN KEY (`id_ponente`)
    REFERENCES `djary`.`ponente` (`id_ponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`promocion` (
  `id_promocion` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `costo` INT NOT NULL,
  `actividadesNecesarias` INT NOT NULL,
  `descuento` INT NULL,
  `categoria` VARCHAR(25) NULL,
  PRIMARY KEY (`id_promocion`),
  CONSTRAINT `fk_promocion_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `djary`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`asignarActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`asignarActividad` (
  `id_actividad` INT NOT NULL,
  `id_promocion` INT NOT NULL,
  CONSTRAINT `fk_asignarActividad_actividad1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `djary`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignarActividad_promocion1`
    FOREIGN KEY (`id_promocion`)
    REFERENCES `djary`.`promocion` (`id_promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`compraPromocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`compraPromocion` (
  `id_compraPromocion` INT NOT NULL,
  `id_promocion` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_compraPromocion`),
  CONSTRAINT `fk_compra_promocion1`
    FOREIGN KEY (`id_promocion`)
    REFERENCES `djary`.`promocion` (`id_promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `djary`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djary`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djary`.`asistencia` (
  `actividadAsistidas` INT NOT NULL,
  `id_compraPromocion` INT NOT NULL,
  CONSTRAINT `fk_asistencia_compraPromocion1`
    FOREIGN KEY (`id_compraPromocion`)
    REFERENCES `djary`.`compraPromocion` (`id_compraPromocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
